language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules/
addons:
  sonarcloud:
    organization: "cpriego"
script:
  - npm run lint:check
  - npm run test:coverage
  - sonar-scanner